[pytest]
asyncio_mode = auto
log_cli = true
log_cli_level = INFO
markers =
    unit: marks unit tests
filterwarnings =
    ignore::ResourceWarning
    ignore:Exception ignored in
    ignore::pytest.PytestUnraisableExceptionWarning
    ignore::pytest.PytestUnknownMarkWarning
    ignore::pytest.PytestDeprecationWarning
