from typing import Protocol, List, Any, Union, Optional
from imednet.models.codings import Coding
from imednet.models.forms import Form
from imednet.models.intervals import Interval
from imednet.models.jobs import Job, JobStatus
from imednet.models.queries import Query
from imednet.models.record_revisions import RecordRevision
from imednet.models.records import Record
from imednet.models.sites import Site
from imednet.models.studies import Study
from imednet.models.subjects import Subject
from imednet.models.users import User
from imednet.models.variables import Variable
from imednet.models.visits import Visit
from imednet.utils.typing import FilterValue, JsonDict

class ImednetFacade(Protocol):
    def get_codings(self, study_key: str, **filters: FilterValue) -> List[Coding]: ...
    def get_forms(self, study_key: str, **filters: FilterValue) -> List[Form]: ...
    def get_intervals(self, study_key: str, **filters: FilterValue) -> List[Interval]: ...
    def get_job(self, study_key: str, batch_id: str) -> JobStatus: ...
    def get_queries(self, study_key: str, **filters: FilterValue) -> List[Query]: ...
    def get_record_revisions(self, study_key: str, **filters: FilterValue) -> List[RecordRevision]: ...
    def get_records(self, study_key: str, **filters: FilterValue) -> List[Record]: ...
    def get_sites(self, study_key: str, **filters: FilterValue) -> List[Site]: ...
    def get_studies(self, **filters: FilterValue) -> List[Study]: ...
    def get_subjects(self, study_key: str, **filters: FilterValue) -> List[Subject]: ...
    def get_users(self, study_key: str, **filters: FilterValue) -> List[User]: ...
    def get_variables(self, study_key: str, **filters: FilterValue) -> List[Variable]: ...
    def get_visits(self, study_key: str, **filters: FilterValue) -> List[Visit]: ...
    def create_record(self, study_key: str, records_data: List[JsonDict], email_notify: Union[bool, str, None] = None, *, schema: Any = None) -> Job: ...
    def poll_job(self, study_key: str, batch_id: str, timeout: float = 300.0, interval: float = 2.0) -> JobStatus: ...

    @property
    def auth(self) -> Any: ...

class AsyncImednetFacade(Protocol):
    async def async_get_codings(self, study_key: str, **filters: FilterValue) -> List[Coding]: ...
    async def async_get_forms(self, study_key: str, **filters: FilterValue) -> List[Form]: ...
    async def async_get_intervals(self, study_key: str, **filters: FilterValue) -> List[Interval]: ...
    async def async_get_job(self, study_key: str, batch_id: str) -> JobStatus: ...
    async def async_get_queries(self, study_key: str, **filters: FilterValue) -> List[Query]: ...
    async def async_get_record_revisions(self, study_key: str, **filters: FilterValue) -> List[RecordRevision]: ...
    async def async_get_records(self, study_key: str, **filters: FilterValue) -> List[Record]: ...
    async def async_get_sites(self, study_key: str, **filters: FilterValue) -> List[Site]: ...
    async def async_get_studies(self, **filters: FilterValue) -> List[Study]: ...
    async def async_get_subjects(self, study_key: str, **filters: FilterValue) -> List[Subject]: ...
    async def async_get_users(self, study_key: str, **filters: FilterValue) -> List[User]: ...
    async def async_get_variables(self, study_key: str, **filters: FilterValue) -> List[Variable]: ...
    async def async_get_visits(self, study_key: str, **filters: FilterValue) -> List[Visit]: ...
    async def async_create_record(self, study_key: str, records_data: List[JsonDict], email_notify: Union[bool, str, None] = None, *, schema: Any = None) -> Job: ...
    async def async_poll_job(self, study_key: str, batch_id: str, timeout: float = 300.0, interval: float = 2.0) -> JobStatus: ...

