blank_issues_enabled: false
contact_links:
  - name: Ask a question / Discuss
    url: https://github.com/FrederickdeRuiter/imednet-python-sdk/discussions/new?category=q-a
    about: Ask questions and discuss with other community members.
