permissions:
  contents: read
name: Smoke

on:
  workflow_dispatch:

jobs:
  smoke:
    if: github.actor == github.repository_owner
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - uses: abatilo/actions-poetry@v2
      - name: Install dependencies
        run: |
          poetry install --with dev
      - name: Post smoke record
        env:
          IMEDNET_API_KEY: ${{ secrets.APIKEY }}
          IMEDNET_SECURITY_KEY: ${{ secrets.SECURITYKEY }}
          IMEDNET_BASE_URL: ${{ vars.BASE_URL }}
        run: |
          poetry run python scripts/post_smoke_record.py --verbose 2>&1 | tee smoke.log
      - name: Upload smoke log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: smoke-log
          path: smoke.log
      - name: Run live tests
        env:
          IMEDNET_API_KEY: ${{ secrets.APIKEY }}
          IMEDNET_SECURITY_KEY: ${{ secrets.SECURITYKEY }}
          IMEDNET_RUN_E2E: "1"
        run: |
          poetry run pytest -vv -s --log-cli-level=INFO tests/live
