name: Smoke

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - uses: abatilo/actions-poetry@v2
      - name: Install dependencies
        run: |
          poetry install --with dev
      - name: Run live tests
        env:
          IMEDNET_API_KEY: ${{ secrets.APIKEY }}
          IMEDNET_SECURITY_KEY: ${{ secrets.SECURITYKEY }}
          IMEDNET_RUN_E2E: "1"
        run: |
          poetry run pytest -q tests/live
